# Generated by Django 5.1.4 on 2024-12-18 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_logo', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
                ('name_hotel', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('points_natural', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_eco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_socio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
