# Generated by Django 5.1.4 on 2024-12-23 22:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_points_eco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hotel_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_to),
        ),
    ]
