# Generated by Django 4.2.14 on 2024-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_type_resultado_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
