# Generated by Django 5.1.4 on 2024-12-23 22:18

import django.db.models.deletion
import surveys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'solución',
                'verbose_name_plural': 'soluciones',
            },
        ),
        migrations.CreateModel(
            name='Applied_solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=surveys.models.custom_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solutionsApplied', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_applied', to='surveys.solutions')),
            ],
            options={
                'verbose_name': 'solución aplicada',
                'verbose_name_plural': 'soluciones aplicadas',
            },
        ),
    ]
