# Generated by Django 5.1.4 on 2024-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_answer_value_solutions_applied_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='title_solution',
            field=models.TextField(blank=True, default='Título predeterminado', max_length=100, null=True),
        ),
    ]
